services:
  order_service:
    build:
      context: ../services/order_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/inventory_db
    depends_on:
      - db

  product_service:
    build:
      context: ../services/product_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/inventory_db
    depends_on:
      - db

  user_service:
    build:
      context: ../services/user_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/inventory_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
