apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: inventory-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: deployment-order_service:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:root@postgres-service:5432/inventory_db"
