apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: inventory-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: deployment-product_service:latest   # Replace with your built image
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:root@postgres-service:5432/inventory_db"
