apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: inventory-ns
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003
  selector:
    app: user-service
